name: Build and Deploy API

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AZURE_NODE_WEBAPP_NAME: api-app-api-node-REST-jvw-demo
  AZURE_NODE_WEBAPP_PACKAGE_PATH: './apps/nodeAPI'    
  NODE_VERSION: '14.x'

  AZURE_PYTHON_WEBAPP_NAME: api-app-api-python-graph-jvw-demo    
  AZURE_PYTHON_WEBAPP_PACKAGE_PATH: './apps/pythonAPI'
  
  AZURE_PYTHON_WEBAPP_NAME_REST: api-app-api-python-jvw-demo    
  AZURE_PYTHON_WEBAPP_ROOT: './apps/pythonAPIREST/'
  AZURE_PYTHON_WEBAPP_PACKAGE_PATH_REST: './apps/pythonAPIREST/dist/'
jobs:
  build-and-deploy:
    defaults:
      run:
        working-directory: ${{ env.AZURE_NODE_WEBAPP_PACKAGE_PATH }}
    name: Build and Deploy NodeJS API
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build cp node_modules to /dist folder
      run: |
        npm install
        npm run compile
        cp -r node_modules/ dist/
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_NODE_WEBAPP_NAME }}
        package: ${{ env.AZURE_NODE_WEBAPP_PACKAGE_PATH }}/dist      
  build:
    defaults:
      run:
        working-directory: ${{ env.AZURE_PYTHON_WEBAPP_PACKAGE_PATH }}
    name: Build and Deploy GraphQL API
    environment: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt
    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_PYTHON_WEBAPP_NAME }}
        package: ${{ env.AZURE_PYTHON_WEBAPP_PACKAGE_PATH }}
  build_restapi:
    defaults:
      run:
        working-directory: ${{ env.AZURE_PYTHON_WEBAPP_ROOT }}
    name: Build and Deploy PYTHON REST API
    environment: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        python setup.py bdist_wheel 
    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_PYTHON_WEBAPP_NAME_REST }}
        package: ${{ env.AZURE_PYTHON_WEBAPP_PACKAGE_PATH_REST }}
        startup-command: "pip install *.whl && python -m uvicorn users.app:app --host 0.0.0.0"