name: Deploy infra

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Check out sources'
      uses: actions/checkout@v2
    - name: 'Deploy infrastructure'
      run: bash -c './infra/infra-deploy.azcli'
